# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'geo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgeo.proto\x12\x03geo\"F\n\nGeoRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x17\n\x0finclude_sources\x18\x03 \x01(\x08\".\n\x0bGeoResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t29\n\rGeoLLMService\x12(\n\x03\x41sk\x12\x0f.geo.GeoRequest\x1a\x10.geo.GeoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOREQUEST']._serialized_start=18
  _globals['_GEOREQUEST']._serialized_end=88
  _globals['_GEORESPONSE']._serialized_start=90
  _globals['_GEORESPONSE']._serialized_end=136
  _globals['_GEOLLMSERVICE']._serialized_start=138
  _globals['_GEOLLMSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
